/* eslint-disable @typescript-eslint/naming-convention */
export enum Operators {
  RPAREN = ")",
  RBRACKET = "]",
  RBRACE = "}",
  LPAREN = "(",
  STAR = "*",
  PLUS = "+",
  COMMA = ",",
  MINUS = "-",
  RARROW = "->",
  DOT = ".",
  SLASH = "/",
  COLON = ":",
  SEMI = ";",
  EQUALS = "=",
  LBRACKET = "[",
  LBRACE = "{",
}

export enum Symbols {
  BSLASH = "\\",
  COMMENT = "#",
  PREANNOTATION = "@",
  POSTANNOTATION = "@<",
  QUOTE = '"',
  TQUOTE = '"""',
}

export enum Token {
  annotation = "annotation",
  component = "component",
  instance = "instance",
  namespace = "namespace",
  class = "class",
  enum = "enum",
  interface = "interface",
  struct = "struct",
  typeParameter = "typeParameter",
  type = "type",
  parameter = "parameter",
  variable = "variable",
  property = "property",
  enumMember = "enumMember",
  decorator = "decorator",
  event = "event",
  function = "function",
  method = "method",
  macro = "macro",
  label = "label",
  comment = "comment",
  string = "string",
  keyword = "keyword",
  number = "number",
  regexp = "regexp",
  operator = "operator",
  component_kind = "component-kind",
  declaration = "declaration",
  definition = "definition",
  readonly = "readonly",
  static = "static",
  deprecated = "deprecated",
  abstract = "abstract",
  async = "async",
  modification = "modification",
  documentation = "documentation",
  defaultLibrary = "defaultLibrary",
}

export enum Types {
  // Numeric types
  F32 = "variable",
  F64 = "variable",
  I16 = "variable",
  I32 = "variable",
  I64 = "variable",
  I8 = "variable",
  U16 = "variable",
  U32 = "variable",
  U64 = "variable",
  U8 = "variable",
  // Unique types
  constant = "variable",
  bool = "variable",
  array = "variable",
  string = "string",
  struct = "struct",
  enum = "enum",
  // Abstract type
  type = "type",
}

export enum KeywordModifiers {
  active = "component-kind",
  passive = "component-kind",
  queued = "component-kind",
  constant = "readonly",
}

export enum KeywordTokens {
  module = "namespace",
  component = "component",
  instance = "instance",
  port = "port",
}

export enum Keywords {
  // Tokens
  module = "namespace",
  component = "component",
  instance = "instance",
  port = "port",
  // Modifiers
  active = "component-kind",
  passive = "component-kind",
  queued = "component-kind",
  constant = "readonly",
  //
  activity = "",
  always = "",
  assert = "",
  async = "async",
  at = "peroperty",
  base = "parametr",
  block = "property",
  change = "",
  command = "type",
  connections = "event",
  cpu = "operator",
  default = "number",
  diagnostic = "type",
  drop = "type",
  event = "type",
  false = "keyword",
  fatal = "type",
  format = "string",
  get = "type",
  guarded = "type",
  health = "type",
  high = "type",
  id = "keyword",
  import = "definition",
  include = "definition",
  input = "",
  internal = "declaration",
  locate = "declaration",
  low = "type",
  match = "",
  on = "keyword",
  opcode = "keyword",
  orange = "property",
  output = "type",
  param = "",
  phase = "keyword",
  priority = "keyword",
  private = "keyword",
  queue = "keyword",
  recv = "type",
  red = "property",
  ref = "annotation",
  reg = "type",
  resp = "type",
  save = "keyword",
  serial = "type",
  set = "keyword",
  severity = "keyword",
  size = "keyword",
  stack = "keyword",
  sync = "type",
  telemetry = "keyword",
  text = "string",
  throttle = "keyword",
  time = "keyword",
  topology = "keyword",
  true = "keyword",
  update = "keyword",
  warning = "type",
  with = "keyword",
  yellow = "property",
}
